version: '3.8'

services:
  season-transfer-app:
    build: .
    container_name: season_transfer
    ports:
      - "8501:8501"
    volumes:
      # Map the local saved_models directory to the container
      - ./saved_models:/app/saved_models
    environment:
      - ENV=production
    restart: unless-stopped
